# Generated by Django 4.2.26 on 2025-11-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_mapping_schedules_table'),
        ('cms', '0001_make_masterdivision_and_masterschecule_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSchedules',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.masterschedules')),
            ],
        ),
    ]
