# Generated by Django 4.2.26 on 2025-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_create_cuti_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='photo',
            field=models.ImageField(default='placeholder.png', upload_to='static/cuti_img'),
            preserve_default=False,
        ),
    ]
