# Generated by Django 4.2.26 on 2025-11-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_add_photo_in_LeaveRequest_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/cuti_img'),
        ),
    ]
