# Generated by Django 4.2.26 on 2025-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_add_note_in_LeaveRequest_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingschedules',
            name='shift_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
