# Generated by Django 4.2.26 on 2026-01-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_user_target_at_leaverequest_tabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_days', models.IntegerField()),
                ('is_requires_attachment', models.BooleanField(default=False)),
                ('max_per_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
