# Generated by Django 4.2.26 on 2026-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_create_master_permission_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpermission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
