# Generated by Django 4.2.26 on 2026-01-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_change_id_to_auto_field_in_master_permission_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingschedules',
            name='is_from_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingschedules',
            name='original_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_schedule', to='cms.masterschedules'),
        ),
    ]
