# Generated by Django 4.2.26 on 2026-01-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_mappingschedules_is_from_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingschedules',
            name='is_from_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingschedules',
            name='original_schedule_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_original_schedule', to='cms.masterschedules'),
        ),
    ]
