# Generated by Django 4.2.26 on 2025-11-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inabsences',
            old_name='date',
            new_name='date_in',
        ),
        migrations.RenameField(
            model_name='inabsences',
            old_name='status',
            new_name='status_in',
        ),
        migrations.AddField(
            model_name='inabsences',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inabsences',
            name='status_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
