# Generated by Django 4.2.26 on 2025-11-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_change_field_at_inabsences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='divisi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
