# Generated by Django 4.2.26 on 2025-11-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_create_mapping_schedules_table'),
        ('app', '0003_create_mapping_schedules_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inabsences',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.masterschedules'),
        ),
    ]
