# Generated by Django 4.2.26 on 2025-11-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_foreign_key_schedule_in_inabsences'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='default@belum_ada_email.com', max_length=100),
            preserve_default=False,
        ),
    ]
