# Generated by Django 4.2.26 on 2025-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_refactor_admins_to_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Super User')], default=0),
        ),
    ]
