# Generated by Django 4.2.26 on 2025-11-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_field_isadmin_in_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
