# Generated by Django 4.2.26 on 2025-12-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_face_encoding_field_id_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inabsences',
            name='shift_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
