# Generated by Django 4.2.26 on 2026-01-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_change_id_to_auto_field_in_master_permission_table'),
        ('app', '0009_add_boos_id_at_users_tabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='boss_di',
        ),
        migrations.CreateModel(
            name='PermissionRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/bukti_izin')),
                ('note', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.masterpermission')),
                ('user_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_approver', to='app.users')),
            ],
        ),
    ]
