# Generated by Django 4.2.26 on 2026-01-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_create_permission_request_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequests',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_izin/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
