# Generated by Django 4.2.26 on 2026-01-08 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_permissionrequests_photo_alter_users_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_out', models.DateTimeField()),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OUT', 'Sedang Keluar'), ('RETURN', 'Sudah Kembali'), ('CANCEL', 'Dibatalkan')], default='OUT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
