# Generated by Django 4.2.26 on 2026-01-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_create_out_permission_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outpermission',
            old_name='user',
            new_name='nik',
        ),
    ]
