# Generated by Django 4.2.26 on 2026-01-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_user_outpermission_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
