# Generated by Django 4.2.26 on 2026-01-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_mappingschedules_is_from_leave_and_more'),
        ('app', '0014_outpermission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inabsences',
            name='is_from_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inabsences',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.leaverequests'),
        ),
    ]
