# Generated by Django 4.2.26 on 2026-01-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_overtimes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inabsences',
            name='is_from_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inabsences',
            name='permission_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.permissionrequests'),
        ),
    ]
