# Generated by Django 4.2.26 on 2026-02-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_inabsences_is_from_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
