# Generated by Django 4.2.26 on 2026-02-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_users_is_accountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inabsences',
            name='date',
            field=models.DateField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='inabsences',
            constraint=models.UniqueConstraint(fields=('nik', 'date', 'shift_order'), name='unique_absence_per_shift'),
        ),
    ]
