# Generated by Django 4.2.26 on 2026-02-19 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0020_users_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_earning', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('overtime', 'Overtime'), ('per_minute', 'Per Minute'), ('percentage', 'Percentage')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
        ),
    ]
